### PR TITLE
Show updated packages and changed files directly

### PR DESCRIPTION
**Pull request by oyvind-stromsvik**
Edit: This is a proposed change for the pull request body. Forgot to mention that.

Currently updated packages and changed files are hidden behind collapsed details sections, but I feel this is important information that you should read through for every Violinist PR to ensure you know what changes you're actually merging. 

I assume these sections are collapsed because they can become long, but if they are long that's even more reason to read through them. Now if they are long, ie. the PR updates a lot of packages and/or changes a lot of files, you're immediately aware of that fact.

### CODE REVIEW

**Comment by eiriksm** [comment]
I agree with the the reasoning behind changing it for updated packages. But by comparison the changed files are very far from crucial. Could you change it to only display the updated packages and keep the changed files part as is?

**Comment by eiriksm** [comment]
Now you can actually see a preview of your changes and compare them to the currently in use ones (which are always hosted at [https://messages.violinist.io/](https://messages.violinist.io/)

**Review by zaporylie — APPROVED** [review]
I gave a look to the preview and it actually looks quite nice. It helps that the list of updated packages is very short in the preview environment but I agree with the sentiment that if one delays updates causing the list to become much longer the one becomes responsible for the outcome.

My only hope is that we never reach PR body max length (not sure if that's a thing) but that would already be an issue anyways.

**Comment by eiriksm** [comment]
Entirely possible to reach pr body max length. It's 64k on GitHub

**Comment by eiriksm** [comment]
Thanks for comments, testing and feedback. Merging and deploying :tada:

**Pull request merged**
